# Generated by Django 5.2.7 on 2025-10-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripadvisor_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('num_reviews', models.IntegerField(db_index=True, default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('price_level', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('main_image', models.URLField(blank=True, max_length=500)),
                ('num_photos', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('styles', models.JSONField(blank=True, default=list)),
                ('trip_types', models.JSONField(blank=True, default=list)),
                ('subratings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-num_reviews'],
                'indexes': [models.Index(fields=['tripadvisor_id'], name='compilation_tripadv_be87b7_idx'), models.Index(fields=['category', 'rating'], name='compilation_categor_280d21_idx'), models.Index(fields=['country', 'city'], name='compilation_country_d03fb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attractions', models.ManyToManyField(related_name='compilations', to='compilation.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('local', 'Local'), ('touriste', 'Touriste'), ('professionnel', 'Professionnel')], default='touriste', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
