# Generated by Django 5.2.7 on 2025-10-31 18:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilation',
            options={'verbose_name': 'Compilation', 'verbose_name_plural': 'Compilations'},
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='date_created',
        ),
        migrations.AddField(
            model_name='compilation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 31, 18, 24, 14, 842954, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compilation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='compilations', to='compilation.attraction'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compilation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='compilation',
            table='compilations',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
