# Generated by Django 5.2.7 on 2025-10-30 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripadvisor_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('num_reviews', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('num_likes', models.PositiveIntegerField(default=0)),
                ('price_level', models.CharField(blank=True, choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('hotel_style', models.CharField(blank=True, max_length=100)),
                ('attraction_groups', models.CharField(blank=True, max_length=200)),
                ('main_image', models.URLField(blank=True)),
                ('num_photos', models.PositiveIntegerField(default=0)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('target_profiles', models.JSONField(default=list, help_text="Liste des profils ciblés: ['local', 'tourist', 'professional']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-num_likes', '-rating'],
                'indexes': [models.Index(fields=['category'], name='attractions_categor_2f4c97_idx'), models.Index(fields=['city', 'country'], name='attractions_city_886860_idx'), models.Index(fields=['rating'], name='attractions_rating_515bc1_idx'), models.Index(fields=['num_likes'], name='attractions_num_lik_4b31b7_idx'), models.Index(fields=['price_level'], name='attractions_price_l_c7944a_idx')],
            },
        ),
    ]
