# Generated by Django 5.2.7 on 2025-10-31 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('profile_type', models.CharField(choices=[('local', 'Local Explorer'), ('tourist', 'Tourist Traveler'), ('professional', 'Business Professional')], max_length=20)),
                ('budget_range', models.CharField(choices=[('low', '0-100€'), ('medium', '100-500€'), ('high', '500-1000€'), ('luxury', '1000€+')], max_length=10)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_categories', models.JSONField(default=list, help_text="Liste des catégories préférées: ['restaurant', 'attraction', 'hotel']")),
                ('preferred_countries', models.JSONField(blank=True, default=list)),
                ('preferred_price_levels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ma compilation', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='attractions.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompilationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('personal_note', models.TextField(blank=True, help_text='Note personnelle sur cette attraction')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priorité de visite (1=haute, 5=basse)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût estimé personnalisé', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attractions.compilation')),
            ],
            options={
                'ordering': ['priority', '-added_at'],
                'unique_together': {('compilation', 'attraction')},
            },
        ),
    ]
