# Generated by Django 5.2.7 on 2025-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_country',
            field=models.CharField(blank=True, default='France', max_length=100),
        ),
    ]
