# Generated by Django 5.2.7 on 2025-10-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_selected_country'),
    ]

    operations = [
    ]
